apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-box
  labels:
    app: postgresql-box
    tier: database
spec:
  selector:
    matchLabels:
      app: postgresql-box
  template:
    metadata:
      labels:
        app: postgresql-box
        tier: database
    spec:
      containers:
        - image: postgres:15
          name: postgresql-image
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgresDB
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: postegresql-pvc-box
              mountPath: /var/lib/postgresql/data
          imagePullPolicy: IfNotPresent
      volumes:
        - name: postegresql-pvc-box
          persistentVolumeClaim:
              claimName: postgresql-pvc-box
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc-box
  labels:
    app: postgresql-box
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-box
  labels:
    app: postgresql-box
    tier: database
spec:
  selector:
    app: postgresql-box
    tier: database
  ports:
    - port: 5432
      targetPort: 5432
